version: '2.0'
services:
  rasa:
    image: rasa/rasa:2.0.0-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run

  action_server:
    image: rasa/rasa-sdk:2.0.0
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./:/app/actions"
